#!/bin/sh

case $1 in
    -t) TIME=$2
        shift 2;;
esac

FG="#FF`qxr background`"
BG="#FF`qxr foreground`"
FONT=`qxr font`

{
    echo "  $@  " | lemonbar -d -g 200x25+10+10 -p -B $BG -F $FG -f $FONT&
    BAR=$!
    sleep ${TIME:-"5"}
    kill $BAR
} &
