#!/bin/sh

bat_stat=`acpi | grep -o -P -e "\w+(?=,)"`
bat_levl=`acpi | grep -o -P -e "\d+(?=%)"`

case $bat_stat in
    "Discharging")
        chrg_colr="%{F`color -pre "#FF" c3`}"
        output="[v]"
        break;;
    "Charging")
        chrg_colr="%{F`color -pre "#FF" c2`}"
        output="[^]"
        break;;
    *)
        chrg_colr="%{F`color -pre "#FF" c5`}"
        output="[|]"
        break;;
esac

if test $bat_levl -gt 75
then
    bat_colr="%{F`color -pre "#FF" c2`}"
elif test $bat_levl -gt 30
then
    bat_colr="%{F`color -pre "#FF" c3`}"
else
    bat_colr="%{F`color -pre "#FF" c1`}"
fi

if test "$1" = "color"
then
    echo "$chrg_colr $output $bat_colr $bat_levl %{F-}"
else
    echo "$output $bat_levl"
fi
