#!/bin/sh

FONT="-*-gohufont-bold-r-normal-*-14-100-100-100-*-80-iso8859-1,-*-symbola-*-*-*-*-*-*-*-*-*-*-*-*"

### ---
### colors
### ---

BG=#262626  # Gray15
FG=#bfbfbf  # Gray75

#
# normal
#
# black
c0=#0d0d0d  # Gray5
# red
c1=#cd2626  # Firebrick3
# green
c2=#698b22  # OliveDrab4
# yellow
c3=#cd6600  # DarkOrange6
# blue
c4=#53868b  # CadetBlue4
# magenta
c5=#8b668b  # Plum4
# cyan
c6=#4682b4  # SteelBlue
# white
c7=#ffe7ba  # Wheat1


#
# high
#
# black
c8=#1a1a1a  # Gray10
# red
c9=#cd1076  # DeepPink3
# green
c10=#b3ee3a  # OliveDrab2
# yellow
c11=#eeb422  # GoldenRod2
# blue
c12=#1c86ee  #DodgerBlue2
# magenta
c13=#ee7ae9  # Orchid2
# cyan
c14=#00eeee  # Cyan2
# white
c15=#f2f2f2  # Gray95


gen_x_res ()
{
    echo -n "" > .Xresources

    # ---
    # etc
    # ---
    echo "! etc" >> .Xresources
    echo "*scrollBar: false" >> .Xresources
    echo "URxvt*perl-ext-common: default,matcher,clipboard" >> .Xresources
    echo "*font: $FONT" >> .Xresources

    # ---
    # color
    # ---
    echo "" >> .Xresources
    echo "! colors" >> .Xresources
    echo "*background: $BG" >> .Xresources
    echo "*foreground: $FG" >> .Xresources
    echo "*color0: $c0" >> .Xresources
    echo "*color1: $c1" >> .Xresources
    echo "*color2: $c2" >> .Xresources
    echo "*color3: $c3" >> .Xresources
    echo "*color4: $c4" >> .Xresources
    echo "*color5: $c5" >> .Xresources
    echo "*color6: $c6" >> .Xresources
    echo "*color7: $c7" >> .Xresources
    echo "*color8: $c8" >> .Xresources
    echo "*color9: $c9" >> .Xresources
    echo "*color10: $c10" >> .Xresources
    echo "*color11: $c11" >> .Xresources
    echo "*color12: $c12" >> .Xresources
    echo "*color13: $c13" >> .Xresources
    echo "*color14: $c14" >> .Xresources
    echo "*color15: $c15" >> .Xresources

}


get_color ()
{
    echo "${PRE:-"#"}`echo "$1" | cut -b 2-`"
}


case $1 in
    -pre) PRE=$2
        shift 2;;
esac

case $1 in
    bg) get_color $BG;;
    fg) get_color $FG;;
    c0) get_color $c0;;
    c1) get_color $c1;;
    c2) get_color $c2;;
    c3) get_color $c3;;
    c4) get_color $c4;;
    c5) get_color $c5;;
    c6) get_color $c6;;
    c7) get_color $c7;;
    c8) get_color $c8;;
    c9) get_color $c9;;
    c10) get_color $c10;;
    c11) get_color $c11;;
    c12) get_color $c12;;
    c13) get_color $c13;;
    c14) get_color $c14;;
    c15) get_color $c15;;

    gxr) gen_x_res;;

    font) echo $FONT;;
esac
