#!/bin/sh

INACTIVE=`color -pre 0x c0`
ACTIVE=`color -pre 0x c2`


focus ()
{
    if test "$1" != "" && test "$1" != "`pfw`"
    then
        chwb -s 5 -c $INACTIVE `pfw`
        chwso -r $1
        wtf $1
        chwb -s 5 -c $ACTIVE `pfw`
    fi
}


start_d ()
{
    carl | while read wid
    do
        wattr o $wid || focus $wid
    done
}


if test -z $1
then
    start_d
    exit 0
fi

case $1 in
    next) focus `lsw | grep -v $(pfw) | sed '1 p;d'`;;
    prev) focus `lsw | grep -v $(pfw) | sed '$ p;d'`;;
    0x*)  focus $1;;
esac
