#!/bin/sh

info ()
{
    while (true)
    do
        echo %{r}`battery color` `date +"%a %Y-%m-%d %I:%M"` " "
        sleep 1s
    done
}

FG="#ff`qxr foreground`"
BG="#ff`qxr background`"
FONT=`qxr font | cut -d, -f1`
HEIGHT=`qxr systembar.height`

info | lemonbar -db -g x$HEIGHT -B "$BG" -F "$FG" -f "$FONT"
