#!/bin/sh

info ()
{
    while (true)
    do
        echo %{r}`battery color` `date +"%a %Y-%m-%d %I:%M"` " "
        sleep 1s
    done
}

ROOT=`lsw -r`
RW=`wattr w $ROOT`
RH=`wattr h $ROOT`

X=`dc -e "$RW 240 -p"`
Y=`dc -e "$RH 28 -p"`

FG="#ff`qxr foreground`"
BG="#ff`qxr background`"
FONT=`qxr font`

info | lemonbar -db -g x$HEIGHT -B "$BG" -F "$FG" -f "$FONT"
