#!/bin/sh

xrdb ~/.Xresources

# foreground
cmd="\033]10;#$(qxr foreground)\007"
# background
cmd="${cmd}\033]11;#$(qxr background)\007"
# cursor
cmd="${cmd}\033]12;#$(qxr color15)\007"
# highlight background
cmd="${cmd}\033]17;#$(qxr color15)\007"
# highlight foreground
cmd="${cmd}\033]19;#$(qxr color0)\007"

for i in $(seq 0 15);
do
    cmd="${cmd}\033]4;${i};#$(qxr color${i})\007"
done

for term in $(ls /dev/pts/)
do
    echo -n $cmd > /dev/pts/$term
done


killall ibar
ibar &

if test -n `qxr wallpaper`
then
    feh --bg-scale "`qxr wallpaper`"
else
    xsetroot -solid "#$(qxr background)"
fi
