#!/bin/sh

xrdb ~/.Xresources

cmd=""
for i in $(seq 0 15);
do
    cmd="${cmd}\033]4;${i};#$(qxr color${i})\007"
done

for term in $(ls /dev/pts/)
do
    echo -en $cmd > /dev/pts/$term
done


killall ibar
ibar &
