#!/bin/sh

toggle () {
    volstate=`amixer get Master |
                   egrep 'Playback.*?\[o' |
                   egrep -o '\[o.+\]'`

    case "$volstate" in
        *"[on]"*) amixer set Master mute;;
        *"[off]"*) amixer set Master unmute;;
    esac
}

up () {
    amixer set Master 1%+ > /dev/null
}

down () {
    amixer set Master 1%- > /dev/null
}

case $1 in
    "+") up;;
    "-") down;;
    "toggle") toggle;;
esac


perc=`amixer get Master | egrep -o "[0-9]+%" | head -1`
mute=`amixer get Master | egrep -o "(\[o.+\])" | head -1`
case "$mute" in
    *"[on]"*) alert -t 1 "vol: $perc";;
    *"[off]"*) alert -t 1 "vol: $perc [muted]";;
esac
